### ISSUE TITLE
how 头

### ISSUE THREAD

**Issue by qin-young** [raatiniemi/sonar-objective-c#1]
where can I download the plugin binary

**Comment by skywancen** [comment]
> where can I download the plugin binary

https://bintray.com/raatiniemi/maven/sonar-objective-c-plugin#files/me%2Fraatiniemi%2Fsonar%2Fplugin%2F0.7.6

**Comment by raatiniemi** [comment]
Hey @qin-young, as @skywancen already said, the release is available at my bintray repository. Also, additional [installation instructions are available in the documentation](https://github.com/raatiniemi/sonar-objective-c#install-plugin-on-server).

Please note that the plugin require SonarQube +7.1. If you have any installation issues, feel free to open another issue!
