### ISSUE TITLE
if the version 0.6.4 fix the problem of parsing violations in oclint report

### ISSUE THREAD

**Issue by qin-young** [raatiniemi/sonar-objective-c#2]

**Comment by skywancen** [comment]
> _No description provided._

use report-type xml, not pmd!

**Comment by raatiniemi** [comment]
I'm sorry but I don't really follow what kind of issue you're having, could you please elaborate?

If you have issue with generating the OCLint report, as suggested by @skywancen, there are [sample configuration available if you're using fastlane](https://github.com/raatiniemi/sonar-objective-c/tree/master/sample).
